### ISSUE TITLE
Add a check for the version of webpack

### ISSUE THREAD

**Issue by kentcdodds** [js-dxtools/webpack-validator#152]
If the version is 2, then we can log a warning indicating that it's not supported and should not be used. Thoughts?

**Comment by jonathanewerner** [comment]
👍🏻 makes sense.

**Comment by arshdkhn1** [comment]
Yes. My friend told me about `webpack-validator` but when I tried to run webpack, I got this error
```
[1] "loaders" is required
[2] "rules" is not allowed
error Command failed with exit code 1.
```

**Comment by kentcdodds** [comment]
Would you like to [makeapullrequest.com](http://makeapullrequest.com)? :)

**Comment by arshdkhn1** [comment]
@kentcdodds I would love to but I am not sure whether I can do it or not. I will try though :)

**Comment by arshdkhn1** [comment]
I tried running `npm validate` and got this error -

``` 
> webpack-validator@ validate /home/asd/Documents/git_repos/webpack-validator
> npm-run-all --parallel lint cover build test --sequential check-coverage


> webpack-validator@ test /home/asd/Documents/git_repos/webpack-validator
> cross-env NODE_ENV=test mocha "src/**/*.test.js"


> webpack-validator@ lint /home/asd/Documents/git_repos/webpack-validator
> eslint .


> webpack-validator@ prebuild /home/asd/Documents/git_repos/webpack-validator
> rimraf dist


> webpack-validator@ cover /home/asd/Documents/git_repos/webpack-validator
> cross-env NODE_ENV=test nyc --reporter=lcov --reporter=text --reporter=html mocha "src/**/*.test.js"


> webpack-validator@ build /home/asd/Documents/git_repos/webpack-validator
> babel --ignore *.test.js -d dist src

src/bin/script-parsers.js -> dist/bin/script-parsers.js
src/bin/validate-all-scripts.js -> dist/bin/validate-all-scripts.js
src/bin/validate-config.js -> dist/bin/validate-config.js
src/bin/webpack-validator.js -> dist/bin/webpack-validator.js
src/index.js -> dist/index.js
src/properties/context/index.js -> dist/properties/context/index.js
src/properties/devServer/index.js -> dist/properties/devServer/index.js
src/properties/devtool/index.js -> dist/properties/devtool/index.js
src/properties/entry/index.js -> dist/properties/entry/index.js
src/properties/externals/index.js -> dist/properties/externals/index.js
src/properties/module/index.js -> dist/properties/module/index.js
src/properties/node/index.js -> dist/properties/node/index.js
src/properties/output/index.js -> dist/properties/output/index.js
src/properties/performance/index.js -> dist/properties/performance/index.js
src/properties/plugins/index.js -> dist/properties/plugins/index.js
src/properties/resolve/index.js -> dist/properties/resolve/index.js
src/properties/target/index.js -> dist/properties/target/index.js
src/properties/watchOptions/index.js -> dist/properties/watchOptions/index.js
src/rules/index.js -> dist/rules/index.js
src/rules/no-root-files-node-modules-nameclash.js -> dist/rules/no-root-files-node-modules-nameclash.js
src/types/absolutePath.js -> dist/types/absolutePath.js
src/types/index.js -> dist/types/index.js
src/types/notAbsolutePath.js -> dist/types/notAbsolutePath.js
src/types/urlPart.js -> dist/types/urlPart.js
/home/asd/Documents/git_repos/webpack-validator/test/passing-configs/angular2-webpack-starter.development.js:73
  plugins: [new webpack.optimize.OccurenceOrderPlugin(true), new webpack.optimize.CommonsChunkPlugin({ name: 'polyfills', filename: 'polyfills.bundle.js', minChunks: Infinity }),
            ^

TypeError: webpack.optimize.OccurenceOrderPlugin is not a constructor
    at Object.<anonymous> (angular2-webpack-starter.development.js:73:5)
    at Module._compile (module.js:571:32)
    at loader (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at filePathToConfigObj (index.js:6:16)
    at Array.map (native)
    at Object.<anonymous> (index.js:20:3)
    at Module._compile (module.js:571:32)
    at loader (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (index.test.js:2:1)
    at Module._compile (module.js:571:32)
    at loader (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/asd/Documents/git_repos/webpack-validator/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/asd/Documents/git_repos/webpack-validator/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/home/asd/Documents/git_repos/webpack-validator/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/home/asd/Documents/git_repos/webpack-validator/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
/home/asd/Documents/git_repos/webpack-validator/test/passing-configs/angular2-webpack-starter.development.js:73
  plugins: [new webpack.optimize.OccurenceOrderPlugin(true), new webpack.optimize.CommonsChunkPlugin({ name: 'polyfills', filename: 'polyfills.bundle.js', minChunks: Infinity }),
            ^

TypeError: webpack.optimize.OccurenceOrderPlugin is not a constructor
    at Object.<anonymous> (angular2-webpack-starter.development.js:73:5)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (/home/asd/Documents/git_repos/webpack-validator/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at loader (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:126:5)
    at require.extensions.(anonymous function) (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:136:7)
    at Object.<anonymous> (/home/asd/Documents/git_repos/webpack-validator/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at filePathToConfigObj (index.js:6:16)
    at Array.map (native)
    at Object.<anonymous> (index.js:20:3)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (/home/asd/Documents/git_repos/webpack-validator/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at loader (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:126:5)
    at require.extensions.(anonymous function) (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:136:7)
    at Object.<anonymous> (/home/asd/Documents/git_repos/webpack-validator/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (index.test.js:2:1)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (/home/asd/Documents/git_repos/webpack-validator/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at loader (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:126:5)
    at require.extensions.(anonymous function) (/home/asd/Documents/git_repos/webpack-validator/node_modules/babel-register/lib/node.js:136:7)
    at Object.<anonymous> (/home/asd/Documents/git_repos/webpack-validator/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/asd/Documents/git_repos/webpack-validator/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/asd/Documents/git_repos/webpack-validator/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/home/asd/Documents/git_repos/webpack-validator/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/home/asd/Documents/git_repos/webpack-validator/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (/home/asd/Documents/git_repos/webpack-validator/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/asd/Documents/git_repos/webpack-validator/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/asd/Documents/git_repos/webpack-validator/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Function.runMain (/home/asd/.node-spawn-wrap-6289-30cc0812181b/nodejs:40:10)
  script-parsers.js |    11.76 |        0 |        0 |     12.5 |... 28,30,31,34 |
--------------------|----------|----------|----------|----------|----------------|
All files           |    11.76 |        0 |        0 |     12.5 |                |
--------------------|----------|----------|----------|----------|----------------|

ERROR: test: None-Zero Exit(1);

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "validate"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! webpack-validator@ validate: `npm-run-all --parallel lint cover build test --sequential check-coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-validator@ validate script 'npm-run-all --parallel lint cover build test --sequential check-coverage'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-validator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel lint cover build test --sequential check-coverage
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-validator
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-validator
npm ERR! There is likely additional logging output above.
```

This happens because the webpack version that I am using is `2.2.1`. In Webpack v2 OccurenceOrderPlugin has been renamed to OccurrenceOrderPlugin.  When I downgraded the webpack, error was gone.

**Comment by arshdkhn1** [comment]
Hi, I don't know what is the best possible way to tackle this issue but I think parsing the package.json file to get the version of webpack might be a possible option. I haven't understood how this module works internally  and what's the best possible place to write code. Any thoughts ?

**Comment by kentcdodds** [comment]
Honestly, I don't know this codebase super well. Maybe @jonathanewerner can direct you?
